version: '3.7'
x-node:
  &default-node
  build: ./node
  image: ${JEPSEN_NODE_IMAGE:-jepsen/node:latest}
  env_file: ./secret/node.env
  privileged: true
  networks:
    - jepsen
  ports:
    - ${JEPSEN_PORT:-22}

services:
  control:
    container_name: jepsen-control
    hostname: control
    build: ./control
    image: ${JEPSEN_CONTROL_IMAGE:-jepsen/control:latest}
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    networks:
      - jepsen
  n1:
    << : *default-node
    container_name: jepsen-n1
    hostname: n1
  n2:
    << : *default-node
    container_name: jepsen-n2
    hostname: n2
  n3:
    << : *default-node
    container_name: jepsen-n3
    hostname: n3
  n4:
    << : *default-node
    container_name: jepsen-n4
    hostname: n4
  n5:
    << : *default-node
    container_name: jepsen-n5
    hostname: n5

networks:
  jepsen:
